{{- if not .Values.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "doccano.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "doccano.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  username: {{ .Values.admin.username | b64enc | quote }}
  password: {{ .Values.admin.password | b64enc | quote }}
{{- end }}