{{- if and (ne (.Values.database.type | lower) "sqlite") (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "doccano.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "doccano.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  username: {{ .Values.database.username | b64enc | quote }}
  password: {{ .Values.database.password | b64enc | quote }}
{{- end }}