apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metatron-single.name" . }}-{{ .Values.discovery.name }}
  labels:
{{ include "metatron-single.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "metatron-single.name" . }}-{{ .Values.discovery.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Values.discovery.name }}
    {{- with .Values.discovery.extraLabels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "metatron-single.name" . }}-{{ .Values.discovery.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Values.discovery.name }}
      {{- with .Values.discovery.extraLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "metatron-single.name" . }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "metatron-single.name" . }}-{{ .Values.discovery.name }}-config
      {{- if and .Values.discovery.persistence.enabled }}
        - name: h2-backup
          persistentVolumeClaim:
            claimName: {{ include "metatron-single.name" . }}-{{ .Values.discovery.name }}
      {{- end }}
        - name: ingested-volume
          persistentVolumeClaim:
            claimName: {{ include "metatron-single.name" . }}-polaris
      securityContext:
        {{- toYaml .Values.discovery.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.discovery.name }}
          securityContext:
            {{- toYaml .Values.discovery.securityContext | nindent 12 }}
          image: "{{ .Values.discovery.image }}:{{ .Values.discovery.tag }}"
          imagePullPolicy: {{ .Values.discovery.imagePullPolicy }}
          env:
          - name: METATRON_DB_TYPE
            value: h2
          - name: METATRON_H2_DATA_DIR
            value: /app/h2_backup
          - name: METATRON_POLARIS_HOSTNAME
            value: {{ include "metatron-single.name" . }}-{{ .Values.druid.name }}.{{ .Release.Namespace }}.svc
          - name: METATRON_INGESTED_FOLER
            value: /ingested
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
          - name: ingested-volume
            mountPath: /ingested
        {{- if and .Values.discovery.persistence.enabled }}
          - name: h2-backup
            mountPath: /app/h2_backup
        {{- end }}
          command: ["sh", "/etc/config/run.sh"]
          ports:
            - name: http
              containerPort: 8180
              protocol: TCP
          resources:
            {{- toYaml .Values.discovery.resources | nindent 12 }}
    {{- with .Values.discovery.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.discovery.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
