apiVersion: v1
kind: Service
metadata:
  name: {{ include "metatron-single.name" . }}-{{ .Values.druid.name }}
  labels:
{{ include "metatron-single.labels" . | indent 4 }}
spec:
  type: {{ .Values.druid.service.type }}
  ports:
    - port: 8081
      targetPort: coordinator
      protocol: TCP
      name: coordinator
    - port: 8082
      targetPort: broker
      protocol: TCP
      name: broker
    - port: 8090
      targetPort: overlord
      protocol: TCP
      name: overlord
  selector:
    app.kubernetes.io/name: {{ include "metatron-single.name" . }}-{{ .Values.druid.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Values.druid.name }}
